In [67]:
from tensorflow.keras.preprocessing.text import one_hot

In [68]:
# sentences

sentences = [
  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',


]

In [69]:
vocab_size = 10000


In [70]:
### one hot representation
one_hot_repr=[one_hot(words,vocab_size) for words in sentences]
one_hot_repr

[[3176, 490, 5047, 6475],
 [3176, 490, 5047, 3515],
 [3176, 3173, 5047, 386],
 [2140, 1710, 2047, 6586, 603],
 [2140, 1710, 2047, 6586, 9327],
 [6938, 3176, 3826, 5047, 3913],
 [5872, 1482, 4564, 6586]]

In [71]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [72]:
import numpy as np


In [73]:
sent_length = 8
Embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(Embedded_docs)

[[   0    0    0    0 3176  490 5047 6475]
 [   0    0    0    0 3176  490 5047 3515]
 [   0    0    0    0 3176 3173 5047  386]
 [   0    0    0 2140 1710 2047 6586  603]
 [   0    0    0 2140 1710 2047 6586 9327]
 [   0    0    0 6938 3176 3826 5047 3913]
 [   0    0    0    0 5872 1482 4564 6586]]


In [74]:
dim=10

In [75]:
model=Sequential()
model.add(Embedding(vocab_size, 10, input_length=sent_length))
model.compile('adam', 'mse')

C:\Users\mohan\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [76]:
model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_11 (Embedding)        │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [81]:
Embedded_docs = Embedded_docs.astype('float32')

model.predict(Embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step


array([[[-1.68874860e-02,  2.90363319e-02,  4.94805686e-02,
         -2.12919358e-02,  2.02622749e-02,  3.54415886e-02,
          6.18851185e-03, -4.67693806e-02, -4.66962233e-02,
         -1.95464026e-02],
        [-1.68874860e-02,  2.90363319e-02,  4.94805686e-02,
         -2.12919358e-02,  2.02622749e-02,  3.54415886e-02,
          6.18851185e-03, -4.67693806e-02, -4.66962233e-02,
         -1.95464026e-02],
        [-1.68874860e-02,  2.90363319e-02,  4.94805686e-02,
         -2.12919358e-02,  2.02622749e-02,  3.54415886e-02,
          6.18851185e-03, -4.67693806e-02, -4.66962233e-02,
         -1.95464026e-02],
        [-1.68874860e-02,  2.90363319e-02,  4.94805686e-02,
         -2.12919358e-02,  2.02622749e-02,  3.54415886e-02,
          6.18851185e-03, -4.67693806e-02, -4.66962233e-02,
         -1.95464026e-02],
        [ 7.09096342e-03, -3.31457034e-02, -1.18843690e-02,
         -3.89699452e-02, -4.07068729e-02,  1.05189681e-02,
          4.58031185e-02,  3.35944556e-02,  3.964560

In [82]:
Embedded_docs[0]

array([   0.,    0.,    0.,    0., 3176.,  490., 5047., 6475.],
      dtype=float32)